version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
aws_account_number = "360520317360"
stack_name = "origin-624d3b55-824e-43e8-a48f-fde74a4c9d2b"
s3_prefix = "origin-624d3b55-824e-43e8-a48f-fde74a4c9d2b"
region = "eu-central-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM"
disable_rollback = false
